<?php
echo '';
echo '<!DOCTYPE HTML>';
echo '<html>';
echo '<head>';
echo '<title>Hospital Management System</title>';
echo '<link href="css/style.css" rel="stylesheet" type="text/css"  media="all" />';
echo '<link href='http://fonts.googleapis.com/css?family=Ropa+Sans' rel='stylesheet' type='text/css'>';
echo '<link rel="stylesheet" href="css/responsiveslides.css">';
echo '<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>';
echo '<script src="js/responsiveslides.min.js"></script>';
echo '<script>';
echo '// You can also use "$(window).load(function() {"';
echo '$(function () {';
echo '';
echo '// Slideshow 1';
echo '$("#slider1").responsiveSlides({';
echo 'maxwidth: 1600,';
echo 'speed: 600';
echo '});';
echo '});';
echo '</script>';
echo '</head>';
echo '<body>';
echo '';
echo '<div class="header">';
echo '<!--start-logo-->';
echo '<div class="logo">';
echo '<a href="index.html" style="font-size: 30px;">Hospital Management System</a>';
echo '</div>';
echo '<nav>';
echo '<ul>';
echo '<li class="active"><a href="index.html">Home</a></li>';
echo '<li><a href="contact.php">Contact</a></li>';
echo '<li><a href="#">About</a></li>';
echo '</ul>';
echo '';
echo '</nav>';
echo '';
echo '<div class="clear"> </div>';
echo '<!--end-top-nav-->';
echo '';
echo '<!--end-header-->';
echo '</div>';
echo '<div class="clear"> </div>';
echo '<!--start-image-slider---->';
echo '<div class="image-slider">';
echo '<!-- Slideshow 1 -->';
echo '<ul class="rslides" id="slider1">';
echo '<li><img src="images/homepic1.jpg" alt=""></li>';
echo '<li><img src="images/homepic2.jpg" alt=""></li>';
echo '<li><img src="images/homepic1.jpg" alt=""></li>';
echo '</ul>';
echo '<!-- Slideshow 2 -->';
echo '</div>';
echo '<!--End-image-slider---->';
echo '<div class="clear"> </div>';
echo '<div class="content-grids">';
echo '<div class="wrap">';
echo '<div class="section group">';
echo '';
echo '';
echo '<div class="listview_1_of_3 images_1_of_3">';
echo '<div class="listimg listimg_1_of_2">';
echo '<img src="images/patient.png">';
echo '</div>';
echo '<div class="text list_1_of_2">';
echo '<h3>Patients</h3>';
echo '<p>Register & Book Appointment</p>';
echo '<div class="button"><span><a href="hms/user-login.php">Click Here</a></span></div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="listview_1_of_3 images_1_of_3">';
echo '<div class="listimg listimg_1_of_2">';
echo '<img src="images/doctor.png">';
echo '</div>';
echo '<div class="text list_1_of_2">';
echo '<h3>Doctors Login</h3>';
echo '';
echo '<div class="button"><span><a href="hms/doctor/">Click Here</a></span></div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div class="listview_1_of_3 images_1_of_3">';
echo '<div class="listimg listimg_1_of_2">';
echo '<img src="images/admin1.png">';
echo '</div>';
echo '<div class="text list_1_of_2">';
echo '<h3>Admin Login</h3>';
echo '';
echo '<div class="button"><span><a href="hms/admin">Click Here</a></span></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="wrap">';
echo '<div class="content-box">';
echo '<div class="section group">';
echo '<div class="col_1_of_3 span_1_of_3 frist">';
echo '';
echo '</div>';
echo '<div class="col_1_of_3 span_1_of_3 second">';
echo '</div>';
echo '<div class="col_1_of_3 span_1_of_3 frist">';
echo '';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="clear"> </div>';
echo '<div class= "footer">';
echo '<div class="main-content">';
echo '<div class="left box">';
echo '<h2>About us</h2>';
echo '<div class="content">';
echo '<p>Hospital Management System</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="center box">';
echo '<h2>Address</h2>';
echo '<div class="content">';
echo '<div class="place">';
echo '<span class="fas fa-map-marker-alt"></span>';
echo '<span class="text">Andheri, Mumbai</span><br>';
echo '</div>';
echo '<div class="phone">';
echo '<span class="fas fa-phone-alt"></span>';
echo '<span class="text">+089-765432100</span><br>';
echo '</div>';
echo '<div class="email">';
echo '<span class="fas fa-envelope"></span>';
echo '<span class="text">abc@example.com</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="right box">';
echo '<h2>Contact us</h2>';
echo '<div class="content">';
echo '<form action="#">';
echo '<div class="email">';
echo '<div class="text">Email *</div>';
echo '<textarea rows="2" cols="25" required></textarea>';
echo '</div>';
echo '<div class="msg">';
echo '<div class="text">Message *</div>';
echo '<textarea rows="2" cols="25" required></textarea>';
echo '</div>';
echo '<div class="btn">';
echo '<button type="submit">Send</button>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</body>';
echo '</html>';
echo '';
?>